---
title: 'Paper 1: results'
output:
  word_document:
    reference_docx: template.docx
  pdf_document: default

---

<!-- loading packages, user-defined functions and datasets -->
```{r echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE, include=FALSE}
lib <- c("ggplot2", "dplyr","stringr","knitr","gridExtra",
         "lme4","car","kableExtra", "magick", "grid")
lapply(lib, require, character.only = TRUE)
load(file="ws2.RData")

options(knitr.table.format = 'markdown')
```

<!-- set folder for graphs -->
```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "images/"
)
```

<!-- additional funs -->
```{r echo = FALSE}
grid_arrange_shared_legend <- function(..., nrow = 1,y_title, x_size, y_size,widths1 = 2, widths2=0.2,hjust1=1, x_title, ncol = length(list(...)), position = c("bottom", "right")) {

  plots <- list(...)
  position <- match.arg(position)
  g <- ggplotGrob(plots[[1]] + theme(legend.position = position))$grobs
  legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
  lheight <- sum(legend$height)
  lwidth <- sum(legend$width)
  gl <- lapply(plots, function(x) x + theme(legend.position = "none"))
  gl <- c(gl, nrow = nrow, ncol = ncol)

  combined <- switch(position,
                     "bottom" = arrangeGrob(do.call(arrangeGrob, gl),
                                            legend,
                                            ncol = 1,
                                            heights = unit.c(unit(1, "npc") - lheight, lheight)),
                     "right" = arrangeGrob(do.call(arrangeGrob, gl),
                                           legend,
                                           ncol = 2,
                                           widths = c(widths1, widths2),
                                           left=textGrob(y_title, gp=gpar(fontsize=y_size), rot = 90),
                                           bottom=textGrob(x_title, gp=gpar(fontsize=x_size), vjust = 0, hjust = hjust1)))
  grid.newpage()
  grid.draw(combined)

}

```

### Phonotactic probability


<br>

#### Quantiles table

```{r echo = FALSE}
subtlex_us_pp %>%
  .$unsLBPAV %>%
  quantile(na.rm = TRUE) %>%
  as.matrix() %>%
  t() %>%
  kable()
```

<br>

```{r logpp_main, echo = FALSE, results='asis', fig.width=16, fig.height=9}
plot_pp <- function(df, main_title) {
  ggplot(df, aes(x=section, y=ph_pr_qu1_perc, fill=baby, shape="Q1")) + 
  geom_point(size=4, alpha=0.2) +
  scale_x_continuous(breaks=c(1, seq(5,20, 5))) +
  labs(x = " ", y = " ") +
  ggtitle(main_title) +
  theme(plot.title = element_text(hjust = 0.5, size = 25)) +
  geom_point(aes(x=section, y=ph_pr_qu2_perc, fill=baby, shape="Q2"),size=4, alpha=0.2) + 
  geom_point(aes(x=section, y=ph_pr_qu3_perc, fill=baby, shape="Q3"), size=4,alpha=0.2) + 
  geom_point(aes(x=section, y=ph_pr_qu4_perc, fill=baby, shape="Q4"), size=4,alpha=0.2) + 
  scale_shape_manual("IPhOD Quartile", values=c(`Q1`= 0, `Q2`= 3, `Q3` = 2, `Q4`=1),
                     breaks=c("Q1","Q2", "Q3","Q4"))+
  scale_y_continuous(limits=c(0, 70), breaks=seq(0, 70, by = 10))+
  guides(fill=FALSE)+
  geom_smooth(aes(x=section, y=ph_pr_qu1_perc,linetype="Q1"), fill=NA, colour="black", method="lm", size=0.8)+
  geom_smooth(aes(x=section, y=ph_pr_qu2_perc,linetype="Q2"), fill=NA, colour="black", method="lm", size=0.8)+
  geom_smooth(aes(x=section, y=ph_pr_qu3_perc,linetype="Q3"), fill=NA, colour="black", method="lm", size=0.8)+
  geom_smooth(aes(x=section, y=ph_pr_qu4_perc,linetype="Q4"), fill=NA, colour="black", method="lm", size=0.8)+
  theme(axis.text=element_text(size=18),         legend.text = element_text(size = 20),         legend.title = element_text(size = 20),         legend.key.size = unit(1, "cm"))+     scale_colour_grey(start = 0, end = .9)+
  scale_linetype_manual("IPhOD Quartile", values=c(`Q4` = "dotdash", `Q1` = "longdash",`Q2` = "solid", `Q3`= "dotted"), breaks=c("Q1","Q2", "Q3","Q4"))
}

plot1 <- plot_pp(chi_uni_on_subtlex_us, "Children") 
plot2 <- plot_pp(mod_on_subtlex_us, "Model") 
plot3 <- plot_pp(mot_uni_on_subtlex_us, "Mothers") 

grid_arrange_shared_legend(plot3, plot1, plot2, position = "right", 
                           x_title = "Stage", y_title = "Novel words (%)",
                           x_size = 25, y_size = 25,
                           widths1 = 2, widths2 = 0.5, hjust1 = 1)
```

**Figure.** Breakdown of PP by quartile

